print("Các kiểu dữ liệu cơ bản trong Python:")
print("int:", 123)
print("float:", 3.14)
print("bool:", True)
print("str:", "Hello, Python")
print("list:", [1, 2, 3])
print("tuple:", (1, 2, 3))
print("set:", {1, 2, 3})
print("dict:", {"a": 1, "b":2})
